### ISSUE TITLE
Implementation - ToDo List

### ISSUE THREAD

**Issue by thilinamb** [thilinamb/synopsis#1]
## Major
- [x] Use memory pressure during scale-out.
- [ ] Fine tune the thresholds for dynamic scaling
## Minor
- [x] Suppress verbose logs from Hazelcast
- [ ] Make scripts executable when copying to the distribution.
